# apiVersion: v1
# kind: Secret
# metadata:
#   name: helm-argocd-terraform-tutorial
#   namespace: ${ARGOCD_NAMESPACE}
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://github.com/akfmdl/helm-argocd-terraform-tutorial.git
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-argocd-terraform-tutorial
  namespace: ${ARGOCD_NAMESPACE}
spec:
  project: default
  source:
    chart: nginx helm chart
    targetRevision: ${TARGET_REVISION}
    repoURL: https://github.com/akfmdl/helm-argocd-terraform-tutorial.git
    path: charts/example
  destination:
    server: https://kubernetes.default.svc
    namespace: ${TARGET_NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
