services:
  nginx:
    image: docker.io/goranidocker/nginx-jieun-v2:3b70c5a6654e732ec17a55d03ac04e42f21a1e24
    ports:
      - "30000-32767:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
